# Пример 2

In [1]:
import numpy as np
m = np.matrix('1 2 3 4; 5 6 7 8; 9 1 5 7')
print(m)

[[1 2 3 4]
 [5 6 7 8]
 [9 1 5 7]]


In [2]:
type(m)

numpy.matrix

In [3]:
m = np.array(m)
type(m)

numpy.ndarray

In [4]:
m.shape

(3, 4)

In [5]:
m.max()

9

In [6]:
np.max(m)

9

In [8]:
m = np.matrix(m)
m.max(axis=1)

matrix([[4],
        [8],
        [9]])

In [9]:
m.max(axis=0)

matrix([[9, 6, 7, 8]])

In [10]:
m.mean()

4.833333333333333

In [11]:
m.mean(axis=1)

matrix([[2.5],
        [6.5],
        [5.5]])

In [13]:
m.sum(axis=0)

matrix([[15,  9, 15, 19]])