# Пример 3

In [1]:
import numpy as np
nums = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
letters = np.array(['a', 'b', 'c', 'd', 'a', 'e', 'b'])

In [2]:
less_then_5 = nums < 5
less_then_5

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [3]:
pos_a = letters == 'a'
pos_a

array([ True, False, False, False,  True, False, False])

In [4]:
nums[less_then_5]

array([1, 2, 3, 4])

In [6]:
nums[nums < 5] = 10
print(nums)

[10 10 10 10  5  6  7  8  9 10]


In [7]:
m = np.matrix('1 2 3 4; 5 6 7 8; 9 1 5 7')
print(m)

[[1 2 3 4]
 [5 6 7 8]
 [9 1 5 7]]


In [8]:
mod_m = np.logical_and(m >= 3, m <= 7)
mod_m

matrix([[False, False,  True,  True],
        [ True,  True,  True, False],
        [False, False,  True,  True]])

In [9]:
m[mod_m]

matrix([[3, 4, 5, 6, 7, 5, 7]])

In [10]:
m[m > 7] = 25
print(m)

[[ 1  2  3  4]
 [ 5  6  7 25]
 [25  1  5  7]]
