# Пример 4

In [1]:
import numpy as np
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
np.arange(5, 12)

array([ 5,  6,  7,  8,  9, 10, 11])

In [3]:
np.arange(1, 5, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [5]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.ravel(A)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.ravel(A, order='C')

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.ravel(A, order='F')

array([1, 4, 7, 2, 5, 8, 3, 6, 9])

In [9]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
np.where(a % 2 == 0, a * 10, a / 10)

array([ 0. ,  0.1, 20. ,  0.3, 40. ,  0.5, 60. ,  0.7, 80. ,  0.9])

In [10]:
a = np.random.rand(10)
a

array([0.55642332, 0.37526446, 0.24589265, 0.95861707, 0.18235878,
       0.44916279, 0.67206023, 0.48754707, 0.09085441, 0.14104925])

In [11]:
np.where(a > 0.5, True, False)

array([ True, False, False,  True, False, False,  True, False, False,
       False])

In [12]:
np.where(a > 0.5, 1, -1)

array([ 1, -1, -1,  1, -1, -1,  1, -1, -1, -1])