# Пример 6

In [1]:
import numpy as np

In [2]:
np.random.permutation(7)

array([4, 6, 5, 3, 2, 1, 0])

In [3]:
a = ['a', 'b', 'c', 'd', 'e']
np.random.permutation(a)

array(['a', 'e', 'c', 'd', 'b'], dtype='<U1')

In [5]:
arr = np.linspace(0, 10, 5)
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [6]:
arr_mix = np.random.permutation(arr)
arr_mix

array([ 2.5, 10. ,  5. ,  0. ,  7.5])

In [8]:
index_mix = np.random.permutation(len(arr_mix))
index_mix

array([4, 1, 0, 3, 2])

In [9]:
arr[index_mix]

array([10. ,  2.5,  0. ,  7.5,  5. ])